services:
  db:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      #      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    networks:
      - mysql_network
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - mysql_network
networks:
  mysql_network:
    driver: bridge